#!/usr/bin/env sh
set -e

POSTGRES="psql -U ${DATABASE_USER}"
echo "Creating feeder user ${FEEDER}"
$POSTGRES <<-EOSQL
  CREATE ROLE ${FEEDER} WITH PASSWORD '${FEEDER_PW}' LOGIN;
EOSQL
echo "Creating stats user ${STATS}"
$POSTGRES <<-EOSQL
  CREATE ROLE ${STATS} WITH PASSWORD '${STATS_PW}' LOGIN;
EOSQL
echo "granting privs on ${DATABASE_NAME}"
$POSTGRES <<-EOSQL
  GRANT ALL ON DATABASE ${DATABASE_NAME} TO ${FEEDER};
  GRANT CONNECT,SELECT ON ${DATABASE_NAME} TO ${STATS};
EOSQL
