#!/bin/sh
set -e
POSTGRES="psql --username ${DATABASE_USER}"
echo "Creating feeder user ${FEEDER}"
$POSTGRES <<-EOSQL
  CREATE ROLE ${FEEDER} WITH PASSWORD '${FEEDER_PW}' LOGIN
EOSQL
echo "Creating stats user ${STATS}"
$POSTGRES <<-EOSQL
  CREATE ROLE ${STATS} WITH PASSWORD '${STATS_PW}' LOGIN
EOSQL

echo -e "host ${DATABASE_NAME} ${FEEDER} 0.0.0.0/0 md5" >> "$PGDATA/pg_hba.conf"
echo -e "host ${DATABASE_NAME} ${STATS} 0.0.0.0/0 md5" >> "$PGDATA/pg_hba.conf"

mkdir /var/lib/postgresql/archive
chown postgres:postgres /var/lib/postgresql/archive
